---
title: "Results_bis"
author: "Marion Boisseaux"
date: "01/02/2022"
output: html_document
editor_options: 
  chunk_output_type: inline
---

# To do 


What is missing:
* stomatal densities
* FTH data
* vein densities 
* check gmin function 
* check for outliers -> see Daniela

# Import Paracou dataset


```{r Paracou2020}
library(readr)
library(readr)
Paracou <- read_csv("C:/Users/marion.boisseaux/Dropbox/Mon PC (Jaboty20)/Documents/METRADICA/Metradica_Paracou/Rawdata/Donnees_clean/Traits_Paracou.csv")


FTH2021 <- read_csv("C:/Users/marion.boisseaux/Dropbox/Mon PC (Jaboty20)/Documents/METRADICA/Metradica_Paracou/Rawdata/Donnees_clean/FTHdata2021.csv")

```

```{r FTH2021}
library(readxl)
library(googlesheets4)
library(dplyr)

HydroITV_individuals <- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/1-INnZ563VkNBH8rnSwfWieuGwPo9x9GRSV6jXNzatmM/edit#gid=0", range = "individuals")

HydroITV_traits <- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/1-INnZ563VkNBH8rnSwfWieuGwPo9x9GRSV6jXNzatmM/edit#gid=0", range = "ind_ft")

HydroITV_traits <- rename(HydroITV_traits, FieldCode = Individual)

HydroITV <- filter(HydroITV_individuals, StudyLevel == "tree")

All_HydroITV_indv <- left_join(HydroITV, HydroITV_traits, by = "FieldCode")

Gmin_MB_corr_FTH <- read_excel("C:/Users/marion.boisseaux/Dropbox/Mon PC (Jaboty20)/Documents/METRADICA/Metradica_Paracou/Document/Gmin_MB_corr_FTH.xls", 
    sheet = "Gmin_20210920")

Metradica_individuals <- read_excel("C:/Users/marion.boisseaux/Dropbox/Mon PC (Jaboty20)/Documents/METRADICA/Metradica_Paracou/Document/FTH2021.xlsx", 
    sheet = "metradica")

FTHdata2021 <- left_join( Metradica_individuals, All_HydroITV_indv, by = "TreeFieldNum")

library(rio)
export(FTHdata2021, "FTHdata2021.csv")
```

il manque encore les quelques individus résoltés avec Sylvain dans les indv de Paracou.


```{r Merge Paracou data}
library(dplyr)
library(tidyr)
value <- c(245:260)

A <- full_join(Paracou, FTH2021)
A <- A %>% complete(Code, fill = list(245:260))


```

```{r Daniela}
library(readr)
library(dplyr)
ParacouIndv <- read_csv("C:/Users/marion.boisseaux/Dropbox/Mon PC (Jaboty20)/Documents/METRADICA/Metradica_Paracou/Rawdata/FieldSheet_Clean_OUT_Metradica.csv")
ParacouTraits <- read_csv("C:/Users/marion.boisseaux/Dropbox/Mon PC (Jaboty20)/Documents/METRADICA/Metradica_Paracou/Rawdata/Metradica_Individual_based_Trait_Data_including_replications.csv")

Paracou <- left_join(ParacouIndv, ParacouTraits, by = 'idTree')

Paracou 


```

```{r ptlp}
#ANOVA Camille

#the p-value for one-way ANOVA is less than 0.05 indicates that at least one of the  groups differens from the others. 


library(readxl)
library(tidyverse)
library(ggpubr)
library(rstatix)
library(rstatix)

data <- Paracou

data$Habitat_real<- as.factor(data$Habitat_real)
data$Habitat_preference<-as.factor(data$Habitat_preference)
data$SpecCode_CorrBota<-as.factor(data$SpecCode_CorrBota)
data$My_ptlp<- log(-data$My_ptlp)

#quel type ANOVA? Type I or type II c'est les statistiqus utilisées à l'interieur de l'ANOVA. type II par defaut. 
#anova = comparaison de moyennes qui sont calculés grace à des modèles lineaires

# dire quel est mon modele linaire : souvent c'est lm, le basique de R

modele1 <- lm(My_ptlp~Habitat_preference+Habitat_real, data=data) #sans les interactions. mais sinon la reponse à l'habitat de preference en fonction des espèces on rajoute ":" ou "*" à verifier . * est un raccourci a*b c'est a+b+a:b. c'est à dire comme ca:


modele4<- lm(My_ptlp~Habitat_real, data=data)#pour voir l'effet des sous blocs, des traitements, traitements n fonciton espèce, et espèce.


summary(modele4)
summary(modele1) # dans les coef, mon traitement C0 est mon traitement de reference. A voir comment le faire manuellement si jamais ca change. et mes estimates des treatment D1,D2,D3 sont des valeurs qui s'ajoutent ou s'enlèvent par rapport à la reference. 

plot(modele4)
#pour quantifier et pas juste regarder graphiquement: shapiro-wilk (normalité des residus) et test de levene ou test de bartlett (pour l'homoskedasticity: homogeneité des variances) parce que c'est les hypotheses du modele lineaire qui on a dit : N(0,sigma).le mieux pour pas se prendre la tete : faire representation graphique, un histogram des residus et on regarde si c'est une gaussienne.

hist(modele4$residuals)
#apres les summary, il faut tester la distribution qui doit etre normale pour les résidus. 
# Create a QQ plot of residuals
ggqqplot(residuals(modele4))

# Compute Shapiro-Wilk test of normality, to see if follows normal distribution or not/ the Shapiro-Wilk test did not show evidence of non-normality if p >0.05. (we have 0.0961)
shapiro_test(residuals(modele4))

ggqqplot(data, "My_ptlp", facet.by = "Habitat_real")#il se passe un truc bizarre sur les ptlp de BF


#homogeneity of variance across groups.The p-value of the test is 0.0546, which is more than our significance level of 0.05. Thus, we cannot reject the null hypothesis and conclude that the variance among the three groups is equal.
data %>% levene_test(My_ptlp ~ Habitat_real)
bartlett.test(My_ptlp ~ Habitat_real, data = data)#p-value = 0.1133 less than 0.05 the assumption of equal variances is violated and we can proceed to perform Welch’s ANOVA.



#homogeneity of variance assumption is not met, you can compute the Welch one-way ANOVA test using the function welch_anova_test()[rstatix package]. This test does not require the assumption of equal variances.

#plusieurs manieres de faire une ANOVA

data %>% welch_anova_test(My_ptlp~ Habitat_real) 

#The overall p-value (.135) from the ANOVA table is more than α = .05, which means we cannot reject the null hypothesis that the ptlp values are equal between the 2 habitats.


```

```{r gmin}
#ANOVA Camille

#the p-value for one-way ANOVA is less than 0.05 indicates that at least one of the  groups differens from the others. 


library(readxl)
library(tidyverse)
library(ggpubr)
library(rstatix)
library(rstatix)

data <- Paracou

data$Habitat_real<- as.factor(data$Habitat_real)
data$Habitat_preference<-as.factor(data$Habitat_preference)
data$SpecCode_CorrBota<-as.factor(data$SpecCode_CorrBota)


#quel type ANOVA? Type I or type II c'est les statistiqus utilisées à l'interieur de l'ANOVA. type II par defaut. 
#anova = comparaison de moyennes qui sont calculés grace à des modèles lineaires

# dire quel est mon modele linaire : souvent c'est lm, le basique de R

modele1 <- lm(My_gmin.slope~Habitat_preference+Habitat_real, data=data) #sans les interactions. mais sinon la reponse à l'habitat de preference en fonction des espèces on rajoute ":" ou "*" à verifier . * est un raccourci a*b c'est a+b+a:b. c'est à dire comme ca:


modele4<- lm(My_gmin.slope~Habitat_real, data=data)#pour voir l'effet des sous blocs, des traitements, traitements n fonciton espèce, et espèce.


summary(modele4)
summary(modele1) # dans les coef, mon traitement C0 est mon traitement de reference. A voir comment le faire manuellement si jamais ca change. et mes estimates des treatment D1,D2,D3 sont des valeurs qui s'ajoutent ou s'enlèvent par rapport à la reference. 

plot(modele4)
#pour quantifier et pas juste regarder graphiquement: shapiro-wilk (normalité des residus) et test de levene ou test de bartlett (pour l'homoskedasticity: homogeneité des variances) parce que c'est les hypotheses du modele lineaire qui on a dit : N(0,sigma).le mieux pour pas se prendre la tete : faire representation graphique, un histogram des residus et on regarde si c'est une gaussienne.

hist(modele4$residuals)
#apres les summary, il faut tester la distribution qui doit etre normale pour les résidus. 
# Create a QQ plot of residuals
ggqqplot(residuals(modele4))

# Compute Shapiro-Wilk test of normality, to see if follows normal distribution or not/ the Shapiro-Wilk test did not show evidence of non-normality if p >0.05. (we have 0.0961)
shapiro_test(residuals(modele4))

ggqqplot(data, "My_gmin.slope", facet.by = "Habitat_real")#il se passe un truc bizarre sur les ptlp de BF


#homogeneity of variance across groups.The p-value of the test is 0.0546, which is more than our significance level of 0.05. Thus, we cannot reject the null hypothesis and conclude that the variance among the three groups is equal.
data %>% levene_test(My_gmin.slope ~ Habitat_real)
bartlett.test(My_gmin.slope ~ Habitat_real, data = data)#p-value = 0.1133 more than 0.05 the assumption of equal variances is violated and we can proceed to perform Welch’s ANOVA.



#homogeneity of variance assumption is not met, you can compute the Welch one-way ANOVA test using the function welch_anova_test()[rstatix package]. This test does not require the assumption of equal variances.

#plusieurs manieres de faire une ANOVA

data %>% welch_anova_test(My_gmin.slope~ Habitat_real) 

#The overall p-value (0.067) from the ANOVA table is more than α = .05, which means we cannot reject the null hypothesis that the gmin values are equal between the 2 habitats.

```

```{r}
#ANOVA Camille

#the p-value for one-way ANOVA is less than 0.05 indicates that at least one of the  groups differens from the others. 


library(readxl)
library(tidyverse)
library(ggpubr)
library(rstatix)
library(rstatix)

data <- Paracou

data$Habitat_real<- as.factor(data$Habitat_real)
data$Habitat_preference<-as.factor(data$Habitat_preference)
data$SpecCode_CorrBota<-as.factor(data$SpecCode_CorrBota)
data$My_LSWC_E.per_corr=log(data$My_LSWC_E.per_corr)
data <- rename(data, LSWC = My_LSWC_E.per_corr)


#quel type ANOVA? Type I or type II c'est les statistiqus utilisées à l'interieur de l'ANOVA. type II par defaut. 
#anova = comparaison de moyennes qui sont calculés grace à des modèles lineaires

# dire quel est mon modele linaire : souvent c'est lm, le basique de R

modele1 <- lm(LSWC~Habitat_preference+Habitat_real, data=data) #sans les interactions. mais sinon la reponse à l'habitat de preference en fonction des espèces on rajoute ":" ou "*" à verifier . * est un raccourci a*b c'est a+b+a:b. c'est à dire comme ca:


modele4<- lm(LSWC~Habitat_real, data=data)#pour voir l'effet des sous blocs, des traitements, traitements n fonciton espèce, et espèce.


summary(modele4)
summary(modele1) # dans les coef, mon traitement C0 est mon traitement de reference. A voir comment le faire manuellement si jamais ca change. et mes estimates des treatment D1,D2,D3 sont des valeurs qui s'ajoutent ou s'enlèvent par rapport à la reference. 

plot(modele4)
#pour quantifier et pas juste regarder graphiquement: shapiro-wilk (normalité des residus) et test de levene ou test de bartlett (pour l'homoskedasticity: homogeneité des variances) parce que c'est les hypotheses du modele lineaire qui on a dit : N(0,sigma).le mieux pour pas se prendre la tete : faire representation graphique, un histogram des residus et on regarde si c'est une gaussienne.

hist(modele4$residuals)
#apres les summary, il faut tester la distribution qui doit etre normale pour les résidus. 
# Create a QQ plot of residuals
ggqqplot(residuals(modele4))

# Compute Shapiro-Wilk test of normality, to see if follows normal distribution or not/ the Shapiro-Wilk test did not show evidence of non-normality if p >0.05. (we have 0.0961)
shapiro_test(residuals(modele4))

ggqqplot(data, "LSWC", facet.by = "Habitat_real")#il se passe un truc bizarre sur les ptlp de BF


#homogeneity of variance across groups.The p-value of the test is 0.0546, which is more than our significance level of 0.05. Thus, we cannot reject the null hypothesis and conclude that the variance among the three groups is equal.
data %>% levene_test(LSWC ~ Habitat_real)
bartlett.test(LSWC ~ Habitat_real, data = data)#p-value = 0.1133 more than 0.05 the assumption of equal variances is violated and we can proceed to perform Welch’s ANOVA.



#homogeneity of variance assumption is not met, you can compute the Welch one-way ANOVA test using the function welch_anova_test()[rstatix package]. This test does not require the assumption of equal variances.

#plusieurs manieres de faire une ANOVA

data %>% welch_anova_test(LSWC~ Habitat_real) 

#The overall p-value (0.067) from the ANOVA table is more than α = .05, which means we cannot reject the null hypothesis that the gmin values are equal between the 2 habitats.
```

```{r eval=FALSE, include=FALSE}

library(mvnormtest)
library(dplyr)
library(tidyverse)
data <- Paracou

data <- mutate(data, LSWC = log(data$My_LSWC_E.per_corr))
data <- mutate(data, Ptlp = log(-My_ptlp))
data <- mutate(data, gmin = log(My_gmin.slope))
data <- mutate(data, vein= log(Trait_Major_VD))

data$Habitat_real<- as.factor(data$Habitat_real)
data$Habitat_preference<-as.factor(data$Habitat_preference)
data$SpecCode_CorrBota<-as.factor(data$SpecCode_CorrBota)

gmin <- data$gmin
LSWC <- data$LSWC
vein <- data$vein
ptlp <- data$Ptlp

# MANOVA test
res.man <- manova(cbind(gmin, Ptlp, LSWC, vein) ~ SpecCode_CorrBota, data = data)
summary(res.man)

#used a MANOVA to test for multivariate differences between habitat and species identity. 
#used Mantel tests to evaluate whether matrices of pairwise correlations between all traits were similar among forest habitatsthe twenty four focal tree species.


library(ggplot2)
library(multcompView)
Paracou<- na.omit(Paracou) 

p <- ggplot(Paracou) +
 aes(x = Habitat_preference, y = My_ptlp, fill = Habitat_preference, group = Habitat_preference) +
 geom_boxplot(shape = "circle") +
 scale_fill_manual(values = list(BF = "#8489F4", Generalist = "#9FFB81", 
 TF = "#FFAB61")) +
 labs(y = "Ptlp (MPa)") +
 theme_minimal()+
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(), axis.title.y=element_text(size=20,face="bold"))

#p<-p + stat_compare_means(method = "kruskal.test", aes(label = ..p.signif..),                       label.x = 1.5, label.y = -1)
p<-cld_bxplot_wilcox(Paracou,x=Paracou$Habitat_preference,y=Paracou$My_ptlp,plot = p,nudge = 1)

g <- ggplot(Paracou) +
 aes(x = Habitat_preference, y = My_gmin.slope, fill = Habitat_preference, group = Habitat_preference) +
 geom_boxplot(shape = "circle") +
 scale_fill_manual(values = list(BF = "#8489F4", Generalist = "#9FFB81", 
 TF = "#FFAB61")) +
 labs( y = "gmin (mmol.m-2.s-1)") +
 theme_minimal()+
    theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(), axis.title.y=element_text(size=20,face="bold"))
#g<-g + stat_compare_means(method = "kruskal.test", aes(label = ..p.signif..),  label.x = 1.5, label.y = 10)
g<-cld_bxplot_wilcox(Paracou,x=Paracou$Habitat_preference,y=Paracou$My_gmin.slope,plot = g,nudge = 1)


l <- ggplot(Paracou) +
 aes(x = Habitat_preference, y = My_LSWC_E.per_corr, fill = Habitat_preference, group = Habitat_preference) +
 geom_boxplot(shape = "circle") +
 scale_fill_manual(values = list(BF = "#8489F4", Generalist = "#9FFB81", 
 TF = "#FFAB61")) +
 labs( y = "LSWC (g.g-1)") +
 theme_minimal()+
    theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(), axis.title.y=element_text(size=20,face="bold"))
#l<-l + stat_compare_means(method = "kruskal.test", aes(label = ..p.signif..), label.x = 1.5, label.y = 40)

l<-cld_bxplot_wilcox(Paracou,x=Paracou$Habitat_preference,y=Paracou$My_LSWC_E.per_corr,plot = l,nudge = 1)

v <- ggplot(Paracou) +
 aes(x = Habitat_preference, y = Trait_Major_VD, fill = Habitat_preference, group = Habitat_preference) +
 geom_boxplot(shape = "circle") +
 scale_fill_manual(values = list(BF = "#8489F4", Generalist = "#9FFB81", 
 TF = "#FFAB61")) +
 labs( y = "Major vein density (mm.mm-2)") +
 theme_minimal()+
   theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(), axis.title.y=element_text(size=20,face="bold"))
#v + stat_compare_means(method = "kruskal.test", aes(label = ..p.signif..),         label.x = 1.5, label.y = 1.5)

v<- cld_bxplot_wilcox(Paracou,x=Paracou$Habitat_preference,y=Paracou$Trait_Major_VD,plot = v,nudge = 1)


l2 <- ggplot(Paracou) +
 aes(x = spName_CorrBota.x, y = My_LSWC_E.per_corr, fill = Habitat_real, group = Habitat_real) + scale_fill_manual(values = list(BF = "#8489F4", 
 TF = "#FFAB61")) +
 geom_boxplot(shape = "circle") +
 theme_minimal()+
labs(x = "Species", y = "LSWC")
l2 + stat_compare_means(method = "anova", aes(label = ..p.signif..), 
                        label.x = 1.5, label.y = 40)
g2 <- ggplot(Paracou) +
 aes(x = spName_CorrBota.x, y = My_gmin.slope, fill = Habitat_real, group = Habitat_real) + scale_fill_manual(values = list(BF = "#8489F4", 
 TF = "#FFAB61")) +
 geom_boxplot(shape = "circle") +
 theme_minimal()+
labs(x = "Species", y = "gmin")
g2 + stat_compare_means(method = "anova", aes(label = ..p.signif..), 
                        label.x = 1.5, label.y = 40)
p2 <- ggplot(Paracou) +
 aes(x = spName_CorrBota.x, y = My_ptlp, fill = Habitat_real, group = Habitat_real) + scale_fill_manual(values = list(BF = "#8489F4", 
 TF = "#FFAB61")) +
 geom_boxplot(shape = "circle") +
 theme_minimal()+
labs(x = "Species", y = "Ptlp")
p2 + stat_compare_means(method = "anova", aes(label = ..p.signif..), 
                        label.x = 1.5, label.y = 40)


v2 <- ggplot(Paracou) +
 aes(x = spName_CorrBota.x, y = Trait_Major_VD, fill = Habitat_real, group = Habitat_real) + scale_fill_manual(values = list(BF = "#8489F4", 
 TF = "#FFAB61")) +
 geom_boxplot(shape = "circle") +
 theme_minimal()+
labs(x = "Species", y = "major veins (1st, 2nd, 3rd)")
v2 + stat_compare_means(method = "anova", aes(label = ..p.signif..), 
                        label.x = 1.5, label.y = 40)

library(ggplot2)
library(cowplot)

plot_grid(p, l, g, v, labels = c('A', 'B', 'C', 'D'), label_size = 12)


library(ggpubr)

a<-ggarrange(p, l, g, v,
align='h', labels=c('A', 'B','C','D'),
common.legend = T,
 legend = "right")
```

```{r}
library(FactoMineR)
library(factoextra)
library(Factoshiny)
library(ggplot2)

ggplot(Paracou) +
 aes(x = RWCnr_original, y = My_ptlp, fill = Tree_Dawkins, group = Tree_Dawkins) +
 geom_boxplot(shape = "circle") +
 scale_fill_gradient() +
 theme_minimal()


```

