---
title: "Literature"
author: "Marion Boisseaux"
date: "08/03/2022"
output: html_document
---

# Part five : Notes {-}

# Waterlogging

- From **Abiotic Stress Physiology of Horticultural Crops** *edited by N.K. Srinivasa Rao, K.S. Shivashankara, R.H. Laxman*

Section 1.3 : one of the earliest responses to soil flooding is a reduction in stomatal conductance, inhibition of stomatal aperture. Low O2 level may also reduce hydraulic conductivity and csqtly decrease root permeability. This descrease in hydraulic permeability may b liked to aqaporins [...] limiting water uptake and this leading to internal water deficit. Oxygen deficiency generally induces a rapid reduction in the rate of photoS which is generally considered as the result of reduced stomatal aperture, decrease in leaf chloro content + early leaf senescence and a reduction in LA. Waterlogged soils reduce the translocation of photoS product from 'source' to 'sink' root. As a result, the maintenance of photoS acitivity and accumulation of soluble sugar in roots are clearly important adaptations to flooding. 

Plant responses to waterlogging include low stomatal conductance, decrease in leaf, root, and shoot dev't, changes in osmotic potential and nu uptake, reduced chloro content and photoS.

The oxygen diffusion is 10,000 times slower in waterlogged soils as compared to aerated soil. 

The decrease in Oxygen level in soils affects the bioavailability of nutrients and as well as the ability of root systems to uptake and transport water + mineral nu. Waterlogging also causes inhibition of N-uptake from the soil and reduced leaf concentrations of N, P, K, Ca, Mg in avocado + pea. 

with waterlogging: i should find a decrease of stomatal conductance corrolated with an increase of leaf water potential.