---
title: "Annexes_Paper_Metradica"
author: "Marion Boisseaux"
date: "13/09/2022"
output: html_document
---

#libraries
```{r}
library(tidyverse)
library(ggfortify)
library(dplyr)
library(factoextra) 
library(FactoMineR)
library(Factoshiny)
library(corrplot) 
library(ggpubr)
library(ggfortify)
library(agricolae)
library(rstatix)
library(kableExtra)
library(V.PhyloMaker)
library(ggfortify)
library(ggtree)
library(readxl)
library(lme4)
library(ggeffects) #draw plots of models
library(nlme)
library(sjPlot) #for plotting lmer and glmer mods
library(gridExtra)
library(rio)
library(dplyr)
library(tidyr)
library(janitor)
```

# Species phylo

```{r echo=FALSE, message=FALSE, warning=FALSE}

species <- read_excel("../Metradica_Paracou/Document/Totaux.xlsx", 
    sheet = "subset")

kable(species)

species <- data.frame(taxon = c(
  "Eperua_falcata", 
  "Iryanthera_hostmannii", 
  "Jacaranda_copaia subsp. copaia",
  "Pterocarpus_officinalis",
  "Symphonia_globulifera",
  "Tachigali_melinonii",
  "Virola_surinamensis", 
  "Bocoa_prouacensis",
#  "Chrysophyllum_prieurii",
  "Conceveiba_guianensis",
  "Eschweilera_coriacea",
  "Hymenopus_heteromorphus",
  "Protium_stevensonii",
  "Virola_michelii",
  "Carapa_surinamensis",
#  "Carapa_guianensis",
  "Laetia_procera",
  "Protium_opacum subsp. rabelianum",
 # "Casearia_javitensis",
  "Dicorynia_guianensis",
  "Gustavia_hexapetala",
  "Iryanthera_sagotiana",
  "Licania_membranacea",
  "Poraqueiba_guianensis"
  #"Vouacapoua_americana"
))%>% 
  separate(taxon, c("Genus", "Species"), sep = "_", remove = F)
kable(select(species, Genus, Species), caption = "Studied species.")

```


```{r eval=FALSE, fig.cap="phylogeny", include=FALSE}

species <- dplyr::select(species, taxon , Genus, Species)
paracou <- read_excel("../Metradica_Paracou/Document/Paracou_database20210830.xlsx") %>% 
  dplyr::select(Family, Genus, Species) %>% 
  unique() %>% 
  full_join(species) %>% 
  mutate(species = paste(Genus, Species), genus = Genus, family = Family) %>% 
  dplyr::select(species, genus, family, taxon) %>% 
  mutate(taxon = as.character(taxon))
tree <- phylo.maker(sp.list = paracou, tree = GBOTB.extended, nodes = nodes.info.1, scenarios = "S3")
save(tree, file = "./Results/phylogeny_subset.Rdata")
load("./Results/phylogeny_subset.Rdata")
A<- fortify(tree$scenario.3) %>% 
  mutate(species = gsub("_", " ", label)) %>% 
  left_join(paracou) %>% 
  ggtree(aes(col = taxon), layout="circular") + 
  geom_tiplab2(aes(alpha = !is.na(taxon), size = !is.na(taxon))) +
  theme_tree(legend.position='bottom', legend.text = element_text(face = "italic")) +
  scale_alpha_manual("taxon", values = c(0.2, 4)) +
  scale_size_manual("taxon", values = c(1, 4))


ggsave(file="phylo_subset.svg", plot=A, width=15, height=10)
ggsave(file="phylo_subset.jpg", plot=A, width=15, height=10)
```


#Table sampling

```{r Tab. S1. Individuals per species collected in the three sampling sites. }

Totaux <- read_excel("../Metradica_Paracou/Document/Totaux.xlsx", 
    sheet = "Feuil3")

options(knitr.kable.NA = '') #replace NA by blank spaces in table

Totaux  %>%
  kbl(caption = "Individuals per species collected on the 3 sites") %>% 
  kable_classic(full_width = F, html_font = "Cambria") %>%
  column_spec(2:3, italic = T) %>%
  row_spec(0, bold= T) %>%
  row_spec(26, background = "#666;", color = "white") %>% save_kable(file = "Sampling.png", zoom = 10)



```

## Subset - Table sampling

```{r Tab. S1. Individuals per species collected in the three sampling sites. }

Family <- read.csv("C:/Users/marion.boisseaux/Dropbox/Mon PC (Jaboty20)/Documents/METRADICA/Divers/Species_choice_Indval/Metradica_species_subset_total.csv") %>%
  select(Family, Genus, Species)

Totaux <- read.csv("C:/Users/marion.boisseaux/Dropbox/Mon PC (Jaboty20)/Documents/METRADICA/METRADICAproject/Dataset/OUTPUT_cleaning/Subset_not_imputed/Subset.csv") 

Paracou <- Totaux_subset %>% 
  filter(Forest == "Paracou") %>%
  group_by(Name) %>%
  summarise(Paracou = n())

Bafog <- Totaux_subset %>% 
  filter(Forest == "Bafog") %>%
  group_by(Name) %>%
  summarise(Bafog = n())

Kaw <- Totaux_subset %>% 
  filter(Forest == "Kaw") %>%
  group_by(Name) %>%
  summarise(Kaw = n())

Paracou <- left_join(Paracou, Bafog)

Totaux_table <- left_join(Paracou, Kaw)

Totaux <- Totaux %>% dplyr::select(Genus, Species, Name) %>%unique()

Totaux <-   left_join(Totaux_table, Totaux)%>%
  relocate(Genus, .before =Name) %>%
  relocate(Species, .after = Genus)

Totaux_table <- left_join(Totaux, Family)

Totaux_table <- Totaux_table %>%
  select(-Name) %>%
  relocate(Family, .before="Genus") %>%
  adorn_totals("row")


Totaux_table <- Totaux_table %>%
  replace(is.na(.), 0) %>%
  mutate(Total = rowSums(select(., -Family, -Genus, -Species)))

options(knitr.kable.NA = '') #replace NA by blank spaces in table



Totaux_table %>%
  kbl(caption = "Individuals per species collected on the 3 sites") %>% 
  kable_classic(full_width = F, html_font = "Cambria") %>%
  column_spec(2:3, italic = T) %>%
  row_spec(0, bold= T) %>%
  row_spec(22, background = "#666;", color = "white") %>%
  column_spec(7,  background = "#666;", color = "white" ) %>%
save_kable(file = "../METRADICAproject/Results/Tables_SI/Sampling_subset.png", zoom = 10)



```



#Table indvals

```{r Table S2: Species chosen for the study according to the Indicator values (Indval) within each habitat in French Guiana. }

Indval <- read.csv("C:/Users/marion.boisseaux/Dropbox/Mon PC (Jaboty20)/Documents/METRADICA/Divers/Species_choice_Indval/Metradica_species_subset_total.csv")

Indval <- with(Indval, Indval[order(Type) , ]) #ordering per type

options(knitr.kable.NA = '') #replace NA by blank spaces in table


Indval %>%
  kbl() %>%
  row_spec(0, bold = TRUE) %>% 
  column_spec(1:2, italic = TRUE) %>%
  kable_classic_2(full_width = F) %>% save_kable(file = "../METRADICAproject/Results/Tables_SI/IndVal_subset.png", zoom = 10)

```


